apiVersion: apps/v1
kind: Deployment
metadata:
  name: digital-bank-backends-visa-java-deployment
  namespace: digibank-backends
  labels:
    app: digital-bank-backends-visa-java
    tier: backend
    tier-name: backend-visa    
spec:
  replicas: 1
  selector:
    matchLabels:
      app: digital-bank-backends-visa-java
  template:
    metadata:
      labels:
        app: digital-bank-backends-visa-java
        tier: backend
        tier-name: backend-visa           
    spec:
      containers:
      - name: digital-bank-backends-visa-java
        image: "{{ .Values.image.visa }}"
        resources:
          requests:
            memory: "512M"
            cpu: "500m"
          limits:
            memory: "2048M"
            cpu: "700m"
        ports:
          - name: visa-port
            containerPort: 8081
        env:
          - name: SLOW_ZIP
            value: "14758"
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: "http://otel-collector.otel.svc.cluster.local:4317"
          - name: OTEL_RESOURCE_ATTRIBUTES
            value: "service.name=digibank-java-atm-backend,service.namespace=digibank"             
#          - name: OTEL_SERVICE_NAME
#            value: "digibank"   



