apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: jaeger
  name: jaeger
  namespace: otel
spec:
  type: LoadBalancer
  ports:
  - name: port-1
    port: 16686
    protocol: TCP
    targetPort: 16686
  - name: port-2
    port: 14268
    protocol: TCP
    targetPort: 14268
  - name: port-3
    port: 14250
    protocol: TCP
    targetPort: 14250
  selector:
    app: jaeger
status:
  loadBalancer: {}
