###################################
### DIGITAL BANKING 
# app
#
# Please configure image names in .env file
###################################

version: "3.5"
services:

# =====================================================================
# Digital Broker Service Configuration
# =====================================================================
  broker:
    image: ${BROKER_IMAGE}
    container_name: broker
    hostname: broker
    ports:
      - "8161:8161"
      - "61616:61616"
    restart: unless-stopped

# =====================================================================
# Digital Credit Service Configuration
# =====================================================================    
  credit:
    image: ${CREDIT_IMAGE}
    container_name: credit
    hostname: credit
    environment:

      # Debug Options
      LOGGING_LEVEL_IO_DIGISIC_CREDIT: INFO

      # Digital Broker Connection
      SPRING_ARTEMIS_MODE: native
      SPRING_ARTEMIS_HOST: broker
      SPRING_ARTEMIS_PORT: 61616
      SPRING_ARTEMIS_USER: admin
      SPRING_ARTEMIS_PASSWORD: admin

      # Credit Application Process
      IO_DIGISIC_CREDIT_APP_PROCESS_ENABLED: 'true'
      IO_DIGISIC_CREDIT_APP_PROCESS_TIME: 20

      # Digital Credit Application Process JMS Queues
      IO_DIGISIC_PARTNER_CREDIT_APP_REQUEST: CREDIT.APP.REQUEST
      IO_DIGISIC_PARTNER_CREDIT_APP_RESPONSE: CREDIT.APP.RESPONSE
    depends_on:
      - broker

  bank:
    image: ${BANK_IMAGE}
    container_name: bank
    hostname: bank
    environment:

      # Debug Options
      LOGGING_LEVEL_IO_DIGISIC_BANK: INFO
      
      # Digital Broker connection
      SPRING_ARTEMIS_MODE: native
      SPRING_ARTEMIS_HOST: broker
      SPRING_ARTEMIS_PORT: 61616
      SPRING_ARTEMIS_USER: admin
      SPRING_ARTEMIS_PASSWORD: admin

      # Digital Credit Connection
      IO_DIGISIC_CREDIT_ENABLED: 'true'
      IO_DIGISIC_CREDIT_PROTOCOL: http
      IO_DIGISIC_CREDIT_HOST: credit
      IO_DIGISIC_CREDIT_PORT: 8080
      IO_DIGISIC_CREDIT_CONTEXT-PATH: /credit
      IO_DIGISIC_CREDIT_USERNAME: admin@demo.io
      IO_DIGISIC_CREDIT_PASSWORD: Demo123!

      # Digital Credit Application Process JMS Queues
      IO_DIGISIC_PARTNER_CREDIT_APP_REQUEST: CREDIT.APP.REQUEST
      IO_DIGISIC_PARTNER_CREDIT_APP_RESPONSE: CREDIT.APP.RESPONSE

      # ATM Location Service Connection 
      IO_DIGISIC_BANK_ATM_PROTOCOL: http
      IO_DIGISIC_BANK_ATM_HOST: atm-search
      IO_DIGISIC_BANK_ATM_PORT: 8081

      # VISA Direct Payment Service
      IO_DIGISIC_BANK_VISA_PROTOCOL: http
      IO_DIGISIC_BANK_VISA_HOST: visa
      IO_DIGISIC_BANK_VISA_PORT: 8081
      
      # Open Banking API Service
      IO_DIGISIC_BANK_OBP_ENABLED: 'true'
      IO_DIGISIC_BANK_OBP_CONSUMER_KEY: vwfpvwfr1kngt0up2jelebzmvxrhst4vhxvw1jm3
      IO_DIGISIC_BANK_OBP_VERSION: v4.0.0
      IO_DIGISIC_BANK_OBP_PROTOCOL: https
      IO_DIGISIC_BANK_OBP_HOST:
      IO_DIGISIC_BANK_OBP_PORT:

    ports:
      - "8080:8080"

    depends_on:
      - broker
      - credit
    restart: unless-stopped      

  atm-search:
    image: ${ATM_JAVA_IMAGE}
    container_name: backends-atm-java
    ports:
      - "10081:8081"
    environment:
      # zipcode that causes slowdon
      SLOW_ZIP: 14758
      EXTERNAL_CALL: N
      EXTERNAL_URL: "http://atm-nginx:80"      

    restart: unless-stopped 

  visa:
    image: ${VISA_JAVA_IMAGE}    
    container_name: backends-visa-java
    ports:
      - "10082:8081"
    environment:
      AWS_API_URL: https://pp58dqva7a.execute-api.us-east-1.amazonaws.com/api/
      SLOW_REGION: ABCD1234ABCD123
      SLOW_TIME: 6000

    restart: unless-stopped     

