###################################
### DIGITAL BANKING 
# java backends
# APM agents
# Please configure APM related info in .env file
###################################

version: "3.5"
services:

# APM - AGENT VOLUME (SIDECAR)
  caapm-agent-saas:
    image: leandrobroadcom/docker-apm-agent:20.11
    container_name: caapm-agent
    volumes:
      - agent-volume:/opt/caapm/agent

###################################
### DIGITAL BANKING BACKENDS - BEGIN
###################################

  atm-search:
    image: leandrobroadcom/digitalbank-backend-java:2.0
    container_name: backends-java
    ports:
      - "10081:8081"
    environment:
      # zipcode that causes slowdon
      SLOW_ZIP: 14758

      # APM AGENT VARIABLES
      APMENV_AGENTNAME: "digitalbank_atm_search"
      APMENV_INTROSCOPE_AGENT_HOSTNAME: "${AGENT_ATM_SEARCH_HOST}"
      JAVA_OPTS: "-javaagent:/opt/caapm/agent/wily/Agent.jar"
      APMENV_INTROSCOPE_AGENT_BROWSERAGENT_AUTOINJECTIONENABLED: "false"
      APMENV_AGENTMANAGER_CREDENTIAL: "${AGENT_CREDENTIAL}"
      AGENT_HOME: /opt/caapm/agent/wily

    #APM - ADD AGENT VOLUME
    volumes:
      - agent-volume:/opt/caapm/agent
    restart: unless-stopped

###################################
### DIGITAL BANKING BACKENDS - END
###################################	

#APM ADD AGENT VOLUME
volumes:
  agent-volume:


