###################################
### DIGITAL BANKING 
# java backends
# APM agents
# Please configure APM related info in .env file
###################################

version: "3.5"
services:

###################################
### DIGITAL BANKING BACKENDS - BEGIN
###################################

  atm-search:
    image: leandrobroadcom/digitalbank-backend-java:2.0
    container_name: backends-java
    ports:
      - "8081:8081"
    environment:

      # Debug Options
      SLOW_ZIP: 14758

    #APM - ADD AGENT VOLUME
#    volumes:
#      - agent-volume:/opt/caapm/agent
#    restart: unless-stopped

###################################
### DIGITAL BANKING BACKENDS - END
###################################	