apiVersion: v1
data:
  SPRING_ARTEMIS_MODE: "native"
  LOGGING_LEVEL_IO_DEMO_BANK: "INFO"
  LOGGING_LEVEL_IO_DIGISIC_CREDIT: "INFO"
  SPRING_ARTEMIS_MODE: "native"
  SPRING_ARTEMIS_HOST: "digital-bank-broker-svc"
  SPRING_ARTEMIS_PORT: "61616"
  IO_DIGISIC_CREDIT_APP_PROCESS_ENABLED: "true"
  IO_DIGISIC_CREDIT_APP_PROCESS_TIME: "20"
  IO_DIGISIC_PARTNER_CREDIT_APP_REQUEST: "CREDIT.APP.REQUEST"
  IO_DIGISIC_PARTNER_CREDIT_APP_RESPONSE: "CREDIT.APP.RESPONSE"            
  IO_DIGISIC_CREDIT_ENABLED: "true"
  IO_DIGISIC_CREDIT_PROTOCOL: "http"
  IO_DIGISIC_CREDIT_HOST: "digital-bank-credit-svc"
  IO_DIGISIC_CREDIT_PORT: "8085"
  IO_DIGISIC_CREDIT_CONTEXT-PATH-PATH: "/credit"
  IO_DIGISIC_CREDIT_USERNAME: "admin@demo.io"
  IO_DIGISIC_CREDIT_PASSWORD: "Demo123!"

kind: ConfigMap
metadata:
  name: cm-digibank
  namespace: digibank
