FROM adoptopenjdk:14-jre-hotspot

COPY jar/digibank-java-backends.jar /opt/digisicapis/
WORKDIR /opt/digisicapis/
ENTRYPOINT ["java","-Duser.timezone=America/Sao_Paulo","-jar", "digibank-java-backends.jar"]
