FROM tomcat:9.0
EXPOSE 8080
COPY /war/credit.war /usr/local/tomcat/webapps/
COPY /war/credit_application.properties /usr/local/tomcat/conf/digitalcredit.properties
HEALTHCHECK CMD curl -fail http://localhost:8080/credit/api/v1/health || exit 1
